[package]
name = "rustybox"
version = "0.0.1"
edition = "2021"
authors = ["Stephen Lynch <stepheng.lynch@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/stephenglynch/RustyBox"

[features]
default = ["yes"]
yes = []

[dependencies]
pico-args = "0.5.0"